version: '3'

services:
  db:
    image: postgres
    ports:
      - "${DOCKER_SERVICE_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${DB_USER:-test}
      POSTGRES_PASSWORD: ${DB_PWD:-testpass}
      POSTGRES_DB: ${DB_NAME:-heyjobs}
    env_file:
      - db.env

  scraper:
    build: .
    depends_on:
      - db

  # Waits for the database to be accessible
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:5432

  test:
    build: .
    command: py.test -v
